version: '3.9'

services:
  my-server-web:
    image: nginx:latest
    environment:
      - PARAMETRO_PROVA_ENV=${PARAMETRO_PROVA}
    networks:
      - my-network

  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my-network

  mysql:
    container_name: mysql_container
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:
